### PR TITLE
Remove Error::description(), implement Error::source() (fix #9)

### LINKED ISSUE #9: Implement cause() for Error
It would probably be a good style to return the underlying `Io` error from `Error::cause()`.

### PR DESCRIPTION
**Pull request by marcospb19**
Moved Error into src/error.rs, implemented error::Error with source and
adapted fmt::Display

Also simplified tests macros

### CODE REVIEW

File: src/parser.rs [hunk 1]
```diff
@@ -260,29 +202,20 @@ fn test_get_read_u32_fn() {
...
-    }
-
     let fluff = [0; 24]; // zeros to pad our magic test cases to satisfy the length requirements
 
     {
         let mut reader = vec![1u8, 2, 3];
         reader.extend(fluff.iter().cloned());
         let err = parse_catalog(&reader[..], ParseOptions::new()).unwrap_err();
-        assert_variant!(err, Eof);
+        matches!(err, Eof);
```
Comment (justinas) [inline src/parser.rs]: I am afraid this needs to be `assert!(matches!())`. `matches!()` only returns a boolean, rather than panicing (and thus failing the test) on non-match.

Besides, this would bump the minimum Rust version from 1.31 all the way to 1.42. While we have no policy on minimum supported Rust version, Debian stable, for example, packages 1.41.1. Perhaps we should keep `assert_variant` for now? :thinking:

**Comment by justinas** [comment]
@marcospb19 thank you - all in all, a great PR! I added just one comment.

My only suggestion for next time would be to split unrelated changes into several commits, e.g. move `Error` to a new file in one commit; impl `source()` in another, refactor tests in a third one, etc. This would make it easier to revert part of the changes if needed. But that is my personal preference and it varies greatly from one person to another :slightly_smiling_face:

File: src/parser.rs (hunk 1 above)
Comment (marcospb19) [reply src/parser.rs]: Oops, I forgot to put it in `assert!()`.

> Perhaps we should keep assert_variant for now? thinking

About bumping the versions, I see the good in both options, I'll let you decide what is the best, I can revert those changes if you ask me to.

I personally don't care too much about it, but maybe it is because of my target user base (for the project I'm currently focusing on, where I expect people to use it in rolling-release distros).

**Comment by marcospb19** [comment]
> My only suggestion for next time would be to split unrelated changes into several commits

Thanks for the advice! I usually get confused about what to do, because I see that some people ask the commits to be squashed after, but yeah, I'll definitely do that.

**Comment by marcospb19** [comment]
@justinas, I'm waiting for a response for the `matches!` replacement, I think that you'd want me to revert the changes, but I'm not sure, I'll wait a little more, I think that I have 1 week left for counting this to HacktoberFest

EDIT: I'm also willing to separating the commits as you suggested me :D.

File: src/parser.rs (hunk 1 above)
Comment (justinas) [reply src/parser.rs]: > @justinas, I'm waiting for a response for the `matches!` replacement, I think that you'd want me to revert the changes, but I'm not sure, I'll wait a little more, I think that I have 1 week left for counting this to HacktoberFest
> 
> EDIT: I'm also willing to separating the commits as you suggested me :D.

@marcospb19, I would say, let's be conservative and revert the `matches!` thing. Travis CI should pass having done that.

**Comment by marcospb19** [comment]
@justinas I got some time today, so I did the PR again, and I separated changes in two different commits, one for moving to `src/error.rs`, and other for using `source()` instead of `description()`, removing the deprecated warning, what do you think?

**Comment by justinas** [comment]
@marcospb19 Looks good, will just wait for Travis to pass.

File: src/error.rs [hunk 2]
```diff
@@ -0,0 +1,62 @@
...
+    /// Incorrect syntax encountered while parsing the meta information
+    MalformedMetadata,
+    /// Meta information string was not the first string in the catalog
+    MisplacedMetadata,
+    /// Invalid Plural-Forms metadata
+    PluralParsing,
+    /// An unknown encoding was specified in the metadata
+    UnknownEncoding,
+}
+use Error::*;
```
Comment (justinas) [inline src/error.rs]: Looks like 1.31.0 is peculiar about imports. https://travis-ci.org/github/justinas/gettext/jobs/737549423

This seems to help
```suggestion
use self::Error::*;
```

**Review by justinas — CHANGES_REQUESTED** [review]

**Review by justinas — APPROVED** [review]

**Comment by justinas** [comment]
Thank you!

**Comment by marcospb19** [comment]
Nice! I was looking for another issue to solve, I don't know what https://github.com/justinas/gettext/issues/11 is about
